import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Button, Card, Checkbox, Col, DatePicker, Empty, Form, Input, InputNumber, List, Modal, Progress, Row, Select, Space, Statistic, Tabs, Tag, Typography, Upload, message } from 'antd';
import { DeleteOutlined, FolderAddOutlined, PlusOutlined, PushpinFilled, SaveOutlined, UploadOutlined } from '@ant-design/icons';
import Editor from '@toast-ui/editor';
import '@toast-ui/editor/dist/toastui-editor.css';
import dayjs from 'dayjs';
import './learning.css';
import './learning-refinement.css';
import { getLearningGuide } from './learningGuides.js';

const { Text, Title, Paragraph } = Typography;
const API='/v1/learning';

function MarkdownEditor({value,onChange,onImage}) {
  const host=useRef(null), editor=useRef(null), onChangeRef=useRef(onChange);
  useEffect(()=>{onChangeRef.current=onChange},[onChange]);
  useEffect(()=>{
    editor.current=new Editor({el:host.current,height:'560px',initialEditType:'wysiwyg',previewStyle:'vertical',initialValue:value||'',usageStatistics:false,
      hooks:{addImageBlobHook:async(blob,callback)=>{const url=await onImage(blob); callback(url,blob.name||'图片')}}});
    editor.current.on('change',()=>onChangeRef.current(editor.current.getMarkdown()));
    return()=>editor.current?.destroy();
  },[]);
  return <div ref={host}/>;
}

function DayOneGuide() {
  const [step, setStep] = useState(0);
  const steps = [
    { title: '确认练习接口', body: <><Paragraph>Restful Booker 是专门练习接口测试的公开服务，不需要注册。</Paragraph><a href="https://restful-booker.herokuapp.com/apidoc/index.html" target="_blank" rel="noreferrer">打开 API 文档 ↗</a><div className="endpoint-box"><code>GET https://restful-booker.herokuapp.com/booking</code></div><Paragraph type="secondary">先访问这个地址；看到 bookingid 列表就说明接口可用。</Paragraph></> },
    { title: '配置 Python', body: <><Paragraph>安装 Python 3.11 或 3.12，并勾选 Add Python to PATH。打开 PowerShell 执行：</Paragraph><pre className="guide-code"><code>{`python --version\nmkdir restful-booker-tests\ncd restful-booker-tests\npython -m venv .venv\n.\\.venv\\Scripts\\Activate.ps1\npython -m pip install pytest requests`}</code></pre><Paragraph type="secondary">若 PowerShell 阻止激活，先执行：<code>Set-ExecutionPolicy -Scope CurrentUser RemoteSigned</code></Paragraph></> },
    { title: '配置 Postman', body: <><Paragraph><Tag color="orange">使用英文界面</Tag>Postman 官方目前没有简体中文，不需要安装第三方汉化包。按照下面的英文按钮操作即可：</Paragraph><ol className="postman-steps"><li>点击 <b>New（新建）</b></li><li>选择 <b>HTTP Request（HTTP 请求）</b></li><li>请求方法选择 <b>GET（查询）</b></li><li>在地址栏粘贴下面的 URL</li><li>点击 <b>Send（发送）</b></li></ol><div className="endpoint-box"><code>https://restful-booker.herokuapp.com/booking/1</code></div><Paragraph><b>验收：</b>在下方 <b>Response（响应）</b>区域看到 <b>Status: 200 OK（状态码成功）</b>，Body 中包含 firstname、lastname 和 bookingdates。若 ID 1 不存在，先请求 <code>/booking</code> 列表并换一个 ID。</Paragraph><div className="postman-glossary"><Tag>Params 参数</Tag><Tag>Authorization 认证</Tag><Tag>Headers 请求头</Tag><Tag>Body 请求体</Tag><Tag>Tests 测试脚本</Tag><Tag>Save 保存</Tag></div></> },
    { title: '首个 pytest 用例', body: <><Paragraph>在项目目录创建 <code>test_booking.py</code>：</Paragraph><pre className="guide-code"><code>{`import requests\n\nBASE_URL = "https://restful-booker.herokuapp.com"\n\ndef test_get_booking_list():\n    response = requests.get(f"{BASE_URL}/booking", timeout=10)\n    assert response.status_code == 200\n    bookings = response.json()\n    assert isinstance(bookings, list)\n    assert len(bookings) > 0\n    assert "bookingid" in bookings[0]`}</code></pre><Paragraph>执行 <code>pytest -v</code>。看到 <Tag color="green">1 passed</Tag> 即完成，并把结果与三个断言的含义写进学习笔记。</Paragraph></> },
  ];
  const item = steps[step];
  return <Card className="guide-card" title="🧭 第 1 天执行引导" extra={<Text type="secondary">60–90 分钟</Text>}><div className="guide-steps">{steps.map((x,i)=><button key={x.title} className={i===step?'active':''} onClick={()=>setStep(i)}><span>{i+1}</span>{x.title}</button>)}</div><div className="guide-content"><Title level={4}>{step+1}. {item.title}</Title>{item.body}<Space><Button disabled={!step} onClick={()=>setStep(step-1)}>上一步</Button><Button type="primary" disabled={step===steps.length-1} onClick={()=>setStep(step+1)}>下一步</Button></Space></div></Card>;
}

function DailyExecutionGuide({task}) {
  const [step,setStep]=useState(0);
  if(task.day_number===1)return <DayOneGuide/>;
  const guide=getLearningGuide(task.day_number);
  const pages=[
    {title:'今日目标',body:<><Paragraph>{guide.outcome}</Paragraph><div className="daily-goal"><Tag color="purple">第 {task.day_number} 天</Tag><Tag color="blue">{task.phase}</Tag><Tag>{task.expected_minutes} 分钟</Tag></div><Paragraph type="secondary">先理解目标再开始操作。今天不追求看很多内容，而是留下一个可以检查的成果。</Paragraph></>},
    {title:'分步实操',body:<ol className="daily-actions">{guide.actions.map((action,index)=><li key={action}><span>{index+1}</span><div><b>{action}</b><small>完成后再进入下一步，遇到问题先记录现象和报错。</small></div></li>)}</ol>},
    {title:'命令与示例',body:<><Paragraph>下面是今天最常用的命令或代码骨架，可以复制后根据实际项目修改：</Paragraph><pre className="guide-code"><code>{guide.commands.join('\n')}</code></pre><Paragraph type="secondary">命令执行失败时，把完整命令、报错信息和你的判断写进学习笔记，不要只保存截图。</Paragraph></>},
    {title:'验收与产出',body:<><div className="acceptance-box"><b>完成标准</b><Paragraph>{guide.acceptance}</Paragraph></div><Paragraph><b>今日必须留下：</b>可运行文件或练习结果、关键截图、一篇复盘笔记。完成后勾选今日任务，并填写实际学习分钟、收获和问题。</Paragraph></>},
  ];
  const page=pages[step];
  return <Card className="guide-card" title={`🧭 第 ${task.day_number} 天执行引导 · ${guide.topic}`} extra={<Text type="secondary">按步骤完成</Text>}><div className="guide-steps">{pages.map((item,index)=><button key={item.title} className={index===step?'active':''} onClick={()=>setStep(index)}><span>{index+1}</span>{item.title}</button>)}</div><div className="guide-content"><Title level={4}>{step+1}. {page.title}</Title>{page.body}<Space><Button disabled={!step} onClick={()=>setStep(step-1)}>上一步</Button><Button type="primary" disabled={step===pages.length-1} onClick={()=>setStep(step+1)}>下一步</Button></Space></div></Card>;
}

export function LearningPanel({client}) {
  const [overview,setOverview]=useState(null),[tasks,setTasks]=useState([]),[stats,setStats]=useState(null);
  const [month,setMonth]=useState(dayjs()),[checkin,setCheckin]=useState({actual_minutes:0,gains:'',blockers:'',tomorrow_focus:''});
  const [folders,setFolders]=useState([]),[notes,setNotes]=useState([]),[note,setNote]=useState(null),[query,setQuery]=useState(''),[trash,setTrash]=useState(false);
  const [saveState,setSaveState]=useState('已保存'), timer=useRef(), currentNote=useRef(null), editVersion=useRef(0);
  const [taskModal,setTaskModal]=useState(null),[form]=Form.useForm();
  async function load(){await client.post(`${API}/schedule/reconcile`,{}); const [o,t,f]=await Promise.all([client.get(`${API}/overview`),client.get(`${API}/tasks`),client.get(`${API}/note-folders`)]); setOverview(o);setTasks(t);setFolders(f); if(o.latest_checkin?.checkin_date===String(o.today)) setCheckin(o.latest_checkin);}
  async function loadStats(value=month){setStats(await client.get(`${API}/stats?month=${value.format('YYYY-MM')}`))}
  async function loadNotes(){setNotes(await client.get(`${API}/notes?q=${encodeURIComponent(query)}&trash=${trash}`))}
  useEffect(()=>{load().catch(e=>message.error(e.message))},[]); useEffect(()=>{loadStats().catch(()=>{})},[month]); useEffect(()=>{loadNotes().catch(()=>{})},[query,trash]);
  async function toggle(task,checked){await client.put(`${API}/tasks/${task.id}`,{...task,status:checked?'completed':'pending'});await Promise.all([load(),loadStats()])}
  async function saveCheckin(){await client.put(`${API}/checkins/${overview.today}`,checkin);message.success('今日打卡已保存');await Promise.all([load(),loadStats()])}
  function updateNote(noteId,patch){if(currentNote.current?.id!==noteId)return;const next={...currentNote.current,...patch};currentNote.current=next;setNote(next);setSaveState('保存中…');const version=++editVersion.current;clearTimeout(timer.current);timer.current=setTimeout(()=>saveNote(next,version),1000)}
  async function saveNote(value=currentNote.current,version=editVersion.current){if(!value)return;try{const saved=await client.put(`${API}/notes/${value.id}`,value);setNotes(rows=>rows.map(row=>row.id===saved.id?saved:row));if(currentNote.current?.id===saved.id&&version===editVersion.current){currentNote.current=saved;setNote(saved);setSaveState('已保存')}}catch(e){if(currentNote.current?.id===value.id)setSaveState('保存失败');message.error(e.message)}}
  async function selectNote(next){clearTimeout(timer.current);const previous=currentNote.current;if(previous&&saveState==='保存中…')await saveNote(previous,editVersion.current);editVersion.current+=1;currentNote.current=next;setNote(next);setSaveState('已保存')}
  async function newNote(){const created=await client.post(`${API}/notes`,{title:'未命名笔记',content_markdown:'',tags:[],is_pinned:false});setNotes(rows=>[created,...rows]);await selectNote(created)}
  async function uploadImage(noteId,blob){const fd=new FormData();fd.append('file',blob);const result=await client.post(`${API}/notes/${noteId}/attachments`,fd);return result.url}
  async function submitTask(){const values=await form.validateFields(); const body={...values,planned_date:values.planned_date.format('YYYY-MM-DD'),original_planned_date:taskModal?.original_planned_date||values.planned_date.format('YYYY-MM-DD')}; taskModal?.id?await client.put(`${API}/tasks/${taskModal.id}`,body):await client.post(`${API}/tasks`,body);setTaskModal(null);await load()}
  const phases=useMemo(()=>Object.entries(tasks.reduce((a,t)=>{(a[`${t.planned_date} · 第 ${t.day_number} 天 · ${t.phase}`]??=[]).push(t);return a},{})),[tasks]);
  if(!overview)return <Card loading/>;
  const tabs=[
    {key:'today',label:'🌱 今日学习',children:<div className="learning-today"><Row gutter={[16,16]}><Col xs={24} lg={16}><Card className="hero-card"><Text>现在最重要的一步</Text><Title level={2}>{overview.next_task?.title||'40 天计划已完成 🎉'}</Title><Paragraph>{overview.next_task?.details}</Paragraph><Progress percent={overview.progress}/></Card>{overview.next_task&&<DailyExecutionGuide key={overview.next_task.id} task={overview.next_task}/>}<Card title={`今日任务 · ${overview.today}`} className="section-card"><List dataSource={overview.today_tasks} locale={{emptyText:'今天没有任务'}} renderItem={t=><List.Item><Checkbox checked={t.status==='completed'} onChange={e=>toggle(t,e.target.checked)}><b>{t.title}</b><div><Text type="secondary">{t.details} · {t.expected_minutes} 分钟</Text></div><div><Tag>{t.category}</Tag>验收：{t.acceptance_criteria}</div></Checkbox></List.Item>}/></Card></Col><Col xs={24} lg={8}><Card title="📝 每日复盘"><Form layout="vertical"><Form.Item label="实际学习分钟"><InputNumber min={0} max={1440} value={checkin.actual_minutes} onChange={v=>setCheckin({...checkin,actual_minutes:v||0})}/></Form.Item>{[['gains','今日收获'],['blockers','遇到的问题'],['tomorrow_focus','明日重点']].map(([k,l])=><Form.Item label={l} key={k}><Input.TextArea rows={3} value={checkin[k]} onChange={e=>setCheckin({...checkin,[k]:e.target.value})}/></Form.Item>)}<Button type="primary" block onClick={saveCheckin}>完成今日打卡</Button></Form></Card></Col></Row></div>},
    {key:'plan',label:'🗺️ 学习计划',children:<><Space className="plan-toolbar"><Tag color="blue">原计划 {overview.plan.original_start_date} — {overview.plan.original_end_date}</Tag><Tag color={overview.deadline_risk?'red':'green'}>预计结束 {overview.plan.projected_end_date}</Tag><Button icon={<PlusOutlined/>} onClick={()=>{setTaskModal({});form.resetFields()}}>新增任务</Button></Space><div className="plan-list">{phases.map(([label,rows])=><Card size="small" title={label} key={label}>{rows.map(t=><div className="plan-task" key={t.id} onClick={()=>{setTaskModal(t);form.setFieldsValue({...t,planned_date:dayjs(t.planned_date)})}}><Checkbox checked={t.status==='completed'} onClick={e=>e.stopPropagation()} onChange={e=>toggle(t,e.target.checked)}/><span>{t.category==='复盘'?'✍️':'🧪'} {t.title}</span><Text type="secondary">{t.expected_minutes}m</Text></div>)}</Card>)}</div></>},
    {key:'calendar',label:'📅 打卡日历',children:<><Space className="stats-row"><DatePicker picker="month" value={month} onChange={setMonth}/><Statistic title="打卡天数" value={stats?.checkin_days||0} suffix="天"/><Statistic title="连续打卡" value={stats?.current_streak||0} suffix="天"/><Statistic title="总时长" value={Math.round((stats?.total_minutes||0)/60*10)/10} suffix="小时"/><Statistic title="任务完成率" value={stats?.task_completion_rate||0} suffix="%"/></Space><CalendarGrid month={month} stats={stats}/></>},
    {key:'notes',label:'📒 学习笔记',children:<div className="notes-layout"><aside><Space><Button icon={<FolderAddOutlined/>} onClick={async()=>{const name=prompt('文件夹名称');if(name){await client.post(`${API}/note-folders`,{name});setFolders(await client.get(`${API}/note-folders`))}}}>文件夹</Button><Button type="primary" icon={<PlusOutlined/>} onClick={newNote}>笔记</Button></Space><Input.Search placeholder="搜索标题和正文" allowClear onSearch={setQuery}/><Button type="text" onClick={()=>setTrash(!trash)}>{trash?'返回笔记':'🗑️ 回收站'}</Button>{folders.map(f=><div className="folder" key={f.id}>📁 {f.name}</div>)}</aside><section className="note-list"><List dataSource={notes} locale={{emptyText:<Empty description="还没有笔记"/>}} renderItem={n=><List.Item className={note?.id===n.id?'selected':''} onClick={()=>selectNote(n)}><List.Item.Meta title={<>{n.is_pinned&&<PushpinFilled/>} {n.title}</>} description={(n.content_markdown||'空白笔记').slice(0,70)}/></List.Item>}/></section><main className="note-editor">{note?<><Space className="editor-head"><Input variant="borderless" value={note.title} onChange={e=>updateNote(note.id,{title:e.target.value})}/><Text type={saveState==='保存失败'?'danger':'secondary'}>{saveState}</Text><Button icon={<SaveOutlined/>} onClick={()=>saveNote()}>保存</Button><Upload showUploadList={false} customRequest={async({file,onSuccess,onError})=>{try{await uploadImage(note.id,file);onSuccess()}catch(e){onError(e)}}}><Button icon={<UploadOutlined/>}>附件</Button></Upload><Button danger icon={<DeleteOutlined/>} onClick={async()=>{clearTimeout(timer.current);await client.delete(`${API}/notes/${note.id}`);currentNote.current=null;setNote(null);loadNotes()}}/></Space><MarkdownEditor key={note.id} value={note.content_markdown} onChange={v=>updateNote(note.id,{content_markdown:v})} onImage={blob=>uploadImage(note.id,blob)}/></>:<Empty description="选择或新建一篇笔记"/>}</main><Upload accept=".zip" showUploadList={false} customRequest={async({file,onSuccess,onError})=>{const fd=new FormData();fd.append('file',file);try{const r=await client.post(`${API}/imports/youdao`,fd);message.success(`导入 ${r.success.length}，重复 ${r.duplicates.length}`);loadNotes();onSuccess()}catch(e){message.error(e.message);onError(e)}}}><Button className="import-btn">导入有道 ZIP</Button></Upload></div>}
  ];
  return <div className="learning-space"><div className="learning-heading"><div><Text>个人成长</Text><Title level={2}>📚 学习空间</Title></div><Tag color="purple">{overview.current_phase}</Tag></div><Tabs items={tabs}/><Modal open={!!taskModal} title={taskModal?.id?'编辑任务':'新增任务'} onCancel={()=>setTaskModal(null)} onOk={submitTask}><Form form={form} layout="vertical"><Form.Item name="title" label="任务名称" rules={[{required:true}]}><Input/></Form.Item><Row gutter={12}><Col span={12}><Form.Item name="phase" label="阶段" rules={[{required:true}]}><Input/></Form.Item></Col><Col span={12}><Form.Item name="category" label="分类" initialValue="实操"><Input/></Form.Item></Col></Row><Form.Item name="details" label="操作说明"><Input.TextArea/></Form.Item><Form.Item name="acceptance_criteria" label="验收标准"><Input.TextArea/></Form.Item><Row gutter={12}><Col span={8}><Form.Item name="day_number" label="第几天" rules={[{required:true}]}><InputNumber/></Form.Item></Col><Col span={8}><Form.Item name="expected_minutes" label="分钟" initialValue={60}><InputNumber/></Form.Item></Col><Col span={8}><Form.Item name="planned_date" label="日期" rules={[{required:true}]}><DatePicker/></Form.Item></Col></Row><Form.Item name="status" hidden initialValue="pending"><Input/></Form.Item></Form></Modal></div>;
}

function CalendarGrid({month,stats}){const start=month.startOf('month'),days=month.daysInMonth(),blanks=(start.day()+6)%7;return <div className="calendar"><div className="weekdays">{['一','二','三','四','五','六','日'].map(x=><b key={x}>{x}</b>)}</div><div className="calendar-grid">{Array(blanks).fill(0).map((_,i)=><i key={`b${i}`}/>)}{Array.from({length:days},(_,i)=>{const key=month.date(i+1).format('YYYY-MM-DD'),d=stats?.days?.[key];return <div key={key} className={d?.checked_in?'checked':''} title={d?.checked_in?'已打卡':''}><b>{i+1}</b><span>{d?.checked_in?`✓ ${d.minutes}m`:'—'}</span><small>{d?.total?`${d.completed}/${d.total}`:''}</small></div>})}</div></div>}
