const guides = [
  ['环境与首个接口测试','跑通 Restful Booker 与首个 pytest 用例',['确认 Python、Postman 可用','创建虚拟环境并安装 pytest、requests','发送 GET /booking 请求','运行首个自动化用例'],['python -m venv .venv','.\\.venv\\Scripts\\Activate.ps1','python -m pip install pytest requests','pytest -v'],'终端显示 1 passed，并记录三个断言的作用'],
  ['查询与异常场景','掌握查询接口的正常、边界与异常验证',['在 Postman 请求 GET /booking','从列表取一个 bookingid 查询详情','尝试不存在的 ID、字母 ID 和空 ID','为状态码、结构、字段类型编写 pytest 断言'],['GET /booking','GET /booking/{bookingid}','GET /booking/999999999','pytest -v -k booking'],'至少完成 6 个场景：2 个正常、2 个边界、2 个异常'],
  ['Python 请求封装','把重复请求封装成可复用客户端',['新建 api/booker_client.py','封装 get、post、put、delete 方法','统一 base_url、timeout 和 headers','用客户端重写已有用例'],['mkdir api','class BookerClient:','    def get_booking(self, booking_id):','        return requests.get(f"{self.base_url}/booking/{booking_id}", timeout=10)'],'用例中不再直接拼接 URL，客户端可独立复用'],
  ['Pytest 与断言','理解 pytest 收集规则并写出有效断言',['观察 test_*.py 与 test_* 收集规则','练习状态码、JSON 类型、字段和值断言','使用 pytest.raises 验证异常','运行 10 个独立用例'],['pytest --collect-only','pytest -v','pytest -v -x','pytest -v --tb=short'],'10 个用例全部被收集，失败信息能够定位原因'],
  ['参数化','用一份测试逻辑覆盖多组数据',['找出重复的查询用例','建立参数表：输入、预期状态码','添加 @pytest.mark.parametrize','观察每组数据独立报告'],['@pytest.mark.parametrize("booking_id, expected", [','    (1, 200), (999999999, 404), ("abc", 404),','])'],'至少 4 组数据，删除重复测试代码'],
  ['鉴权与 CRUD 链路','跑通创建、查询、更新、删除完整业务链',['POST /auth 获取 token','POST /booking 创建数据','查询并更新刚创建的数据','删除数据并确认无法再次查询'],['POST /auth','POST /booking','PUT /booking/{id}','DELETE /booking/{id}'],'一条用例完成全链路，失败后也能清理测试数据'],
  ['接口基础阶段复盘','形成可演示的第一阶段成果',['整理接口清单与覆盖场景','补齐至少 15 个用例','整理常见错误与解决方式','录制或口述 5 分钟项目说明'],['pytest -v','pytest --disable-warnings -q'],'15 个用例稳定通过，并能解释测试设计'],
  ['Fixture 与 conftest','复用登录、数据准备与清理逻辑',['创建 conftest.py','编写 client、token fixture','使用 yield 完成数据清理','比较 function 与 session 作用域'],['pytest --fixtures','@pytest.fixture(scope="session")','yield test_data'],'测试文件不再重复登录和清理代码'],
  ['多环境配置','让同一套用例切换测试环境',['创建 config 目录与配置文件','定义 base_url、账号、超时','通过环境变量选择环境','避免把密码直接写入代码'],['$env:TEST_ENV="test"','pytest -v','os.getenv("TEST_ENV", "test")'],'无需改代码即可切换环境，敏感信息不入库'],
  ['测试数据分离','从 JSON/YAML 加载测试数据',['创建 data 目录','把请求体和预期结果移出测试文件','编写加载函数','结合参数化执行数据'],['python -m pip install pyyaml','yaml.safe_load(file)','json.load(file)'],'修改数据文件即可增加用例，不修改测试逻辑'],
  ['请求工具层','统一请求、响应和公共头处理',['设计 request 方法签名','合并公共与临时 headers','统一 timeout 与 JSON 处理','保留原始 response 供断言'],['def request(self, method, path, **kwargs):','    return self.session.request(method, self.base_url + path, timeout=10, **kwargs)'],'所有 API 方法通过同一个请求入口调用'],
  ['日志体系','让失败请求可以快速定位',['配置 logging 格式和级别','记录方法、URL、状态码和耗时','失败时记录响应摘要','避免记录 token 和密码'],['logging.basicConfig(level=logging.INFO)','logger.info("%s %s -> %s", method, url, response.status_code)'],'一次失败能从日志看出请求位置和响应原因'],
  ['异常与清理','处理网络失败和脏数据问题',['为超时和连接错误增加明确报错','只对幂等请求评估重试','使用 fixture yield 保证清理','模拟失败确认清理仍执行'],['requests.Timeout','requests.ConnectionError','try: ... finally: ...'],'用例中途失败后，测试数据仍被删除'],
  ['Pytest 项目交付','把练习整理成别人可运行的项目',['整理目录结构','补充 requirements.txt','编写安装和运行 README','完整执行至少 30 个用例'],['python -m pip freeze > requirements.txt','pytest -v','tree /F'],'新电脑按 README 可在 10 分钟内运行项目'],
  ['SQL 查询基础','熟练使用筛选、排序和分页',['准备练习数据库','练习 SELECT 与 WHERE','练习 ORDER BY 与 LIMIT','记录执行结果和易错点'],['SELECT * FROM users WHERE status = 1;','SELECT * FROM orders ORDER BY created_at DESC LIMIT 10;'],'独立写出 10 条基础查询且结果正确'],
  ['SQL 聚合查询','用聚合回答业务统计问题',['练习 COUNT、SUM、AVG','使用 GROUP BY 分组','使用 HAVING 过滤聚合结果','解释 WHERE 与 HAVING 区别'],['SELECT status, COUNT(*) FROM orders GROUP BY status;','SELECT user_id, SUM(amount) total FROM orders GROUP BY user_id HAVING total > 1000;'],'完成 10 条聚合题并能解释每个结果'],
  ['SQL 多表连接','掌握 INNER JOIN 与 LEFT JOIN',['画出两张表关联字段','编写 INNER JOIN','改为 LEFT JOIN 对比结果','排查一对多导致的重复行'],['SELECT u.name, o.id FROM users u INNER JOIN orders o ON u.id=o.user_id;','SELECT u.name, o.id FROM users u LEFT JOIN orders o ON u.id=o.user_id;'],'能说明两种 JOIN 的差异并完成 8 道题'],
  ['SQL 综合练习','综合运用子查询、连接和聚合',['完成子查询练习','把可替代子查询改写为 JOIN','分析慢查询的筛选条件','累计完成 50 道 SQL 题'],['EXPLAIN SELECT ...','SELECT * FROM orders WHERE user_id IN (SELECT id FROM users WHERE status=1);'],'50 道题保留 SQL 和答案，错误题完成复盘'],
  ['Linux 日志','用命令快速定位服务日志',['练习 tail 实时查看','使用 grep 搜索错误','用 less 分页和检索','组合管道统计错误数量'],['tail -f app.log','grep -n "ERROR" app.log','less app.log','grep "ERROR" app.log | wc -l'],'能在大日志中快速找到指定时间和错误'],
  ['Linux 系统排查','定位进程、端口和资源异常',['查看进程与 CPU/内存','检查端口监听','查看磁盘和内存','整理一份排查顺序'],['ps aux','ss -lntp','df -h','free -m','top'],'能说明“服务无法访问”的完整排查路径'],
  ['真实项目梳理','把工作经历整理成可讲述项目',['写清业务背景和用户','列出个人职责','绘制核心数据流','整理采用的测试策略'],['背景 → 目标 → 职责 → 方法 → 结果'],'形成一页项目说明，能在 3 分钟内讲清楚'],
  ['质量故事','用 STAR 结构表达缺陷与改进',['选择一个高价值缺陷','还原发现与定位过程','说明推动修复的方法','量化最终收益'],['Situation','Task','Action','Result'],'完成 2 个可用于面试的质量案例'],
  ['Git 工作流','掌握日常分支与合并操作',['初始化或检查仓库','创建功能分支并提交','合并分支','人为制造并解决一次冲突'],['git status','git switch -c feature/demo','git add .','git commit -m "Add demo"','git merge feature/demo'],'提交历史清晰，并能解释冲突解决过程'],
  ['Allure 报告','生成可展示的自动化测试报告',['安装 allure-pytest','运行测试生成结果','启动或生成静态报告','为失败用例添加步骤和附件'],['python -m pip install allure-pytest','pytest --alluredir=allure-results','allure serve allure-results'],'报告包含步骤、失败详情和附件'],
  ['Jenkins 入门','让 Jenkins 自动运行测试',['准备 Jenkins 环境','新建 Pipeline 或 Freestyle 任务','配置代码仓库','添加依赖安装和 pytest 命令'],['python -m pip install -r requirements.txt','pytest -v --alluredir=allure-results'],'点击 Build Now 后任务能稳定完成'],
  ['Jenkins 流水线','用 Jenkinsfile 固化构建流程',['创建 Jenkinsfile','定义 checkout、install、test 阶段','归档测试报告','故意制造失败观察结果'],['pipeline {','  stages { stage("Test") { steps { sh "pytest -v" } } }','}'],'代码仓库包含可运行 Jenkinsfile，失败能正确阻断'],
  ['持续集成','打通代码提交到报告的完整链路',['提交一次测试代码变化','触发 Jenkins 构建','执行 pytest 并生成 Allure','检查失败通知和历史趋势'],['git push origin main','pytest --alluredir=allure-results'],'一次提交可自动产生完整测试报告'],
  ['作品集打磨','让项目适合向面试官展示',['删除临时文件和敏感数据','优化 README 首页','添加架构、运行和报告截图','从零演练一次安装'],['git status','python -m pip install -r requirements.txt','pytest -v'],'仓库整洁，README 能引导面试官快速理解'],
  ['简历项目','把项目成果转成量化描述',['提炼项目规模','写清使用技术','描述解决的问题','补充效率或质量收益'],['动作 + 对象 + 方法 + 量化结果'],'完成 3–5 条项目要点，避免只写“负责测试”'],
  ['简历定稿','完成一份岗位匹配的简历',['对照成都目标岗位 JD','调整技能关键词顺序','压缩无关描述','检查格式、错字和联系方式'],['岗位要求 → 证据 → 简历关键词'],'简历控制在 1–2 页，每项技能都有项目证据'],
  ['接口面试题','建立接口测试知识框架',['复习 HTTP 方法与状态码','梳理接口用例设计方法','准备鉴权、幂等和签名问题','口述一次线上接口排障'],['2xx 成功','4xx 客户端问题','5xx 服务端问题'],'独立回答 20 道题，每题包含例子'],
  ['Python/Pytest 面试题','巩固自动化核心知识',['复习数据结构和函数','复习类、异常和文件处理','解释 fixture 与参数化','现场写一个小用例'],['list / dict / set / tuple','fixture / parametrize / mark'],'完成 20 道题和 3 道编码题'],
  ['SQL/Linux 面试题','提升查询与排障表达',['手写 JOIN 和聚合 SQL','解释索引基础','口述日志定位命令','模拟服务不可用排查'],['JOIN / GROUP BY / HAVING','grep / tail / ss / top'],'完成 15 道 SQL 与 15 道 Linux 问题'],
  ['项目表达','稳定讲清自动化项目价值',['准备 1 分钟项目摘要','讲解架构和目录','说明一个技术难点','说明项目收益与不足'],['背景 20 秒 → 架构 60 秒 → 难点 60 秒 → 结果 20 秒'],'录音回听，项目介绍控制在 3–5 分钟'],
  ['开始投递','建立可持续的求职漏斗',['筛选成都匹配岗位','记录公司、岗位和关键词','定制简历后投递','记录日期和后续状态'],['公司 | 岗位 | 匹配度 | 日期 | 状态'],'完成首批有效投递并建立跟踪表'],
  ['投递复盘','根据市场反馈调整策略',['统计查看、沟通和面试比例','对比不同简历版本','补齐频繁出现的关键词','继续投递匹配岗位'],['投递数 → 沟通数 → 面试数 → Offer'],'形成一条明确调整结论并执行'],
  ['短板补强','集中解决反馈中最高频问题',['整理不会或答错的问题','按频率和影响排序','学习最高优先级知识','重新回答并验证'],['问题 → 原因 → 正确答案 → 示例'],'至少关闭 3 个真实暴露的知识缺口'],
  ['全流程模拟面试','在压力下完整演练',['完成自我介绍','回答技术基础问题','演示项目并接受追问','复盘表达、知识和节奏'],['自我介绍 2 分钟','项目介绍 5 分钟','技术问答 30 分钟'],'完成一次 45 分钟模拟并列出改进项'],
  ['最终演示','确保作品集随时可展示',['从干净环境安装依赖','运行全部自动化用例','打开 Allure 报告','按脚本演示核心设计'],['python -m pip install -r requirements.txt','pytest -v --alluredir=allure-results','allure serve allure-results'],'连续演示两次无阻塞，敏感信息已清理'],
  ['收官与持续投递','把 40 天成果转化为求职行动',['复核简历最终版','检查 GitHub 与作品集','总结 40 天能力变化','制定未来两周投递和复习节奏'],['成果清单 | 待补短板 | 投递目标 | 每日复习'],'形成下一阶段行动表，不因计划结束而停止'],
];

export function getLearningGuide(dayNumber) {
  const row = guides[Number(dayNumber) - 1] || guides[0];
  return { topic: row[0], outcome: row[1], actions: row[2], commands: row[3], acceptance: row[4] };
}
