import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Button, Card, Checkbox, Col, DatePicker, Empty, Form, Input, InputNumber, List, Modal, Progress, Row, Select, Space, Statistic, Tabs, Tag, Typography, Upload, message } from 'antd';
import { DeleteOutlined, FolderAddOutlined, PlusOutlined, PushpinFilled, SaveOutlined, UploadOutlined } from '@ant-design/icons';
import Editor from '@toast-ui/editor';
import '@toast-ui/editor/dist/toastui-editor.css';
import dayjs from 'dayjs';
import './learning.css';
import './learning-refinement.css';

const { Text, Title, Paragraph } = Typography;
const API='/v1/learning';

function MarkdownEditor({value,onChange,onImage}) {
  const host=useRef(null), editor=useRef(null), onChangeRef=useRef(onChange);
  useEffect(()=>{onChangeRef.current=onChange},[onChange]);
  useEffect(()=>{
    editor.current=new Editor({el:host.current,height:'560px',initialEditType:'wysiwyg',previewStyle:'vertical',initialValue:value||'',usageStatistics:false,
      hooks:{addImageBlobHook:async(blob,callback)=>{const url=await onImage(blob); callback(url,blob.name||'图片')}}});
    editor.current.on('change',()=>onChangeRef.current(editor.current.getMarkdown()));
    return()=>editor.current?.destroy();
  },[]);
  useEffect(()=>{if(editor.current&&editor.current.getMarkdown()!==(value||'')) editor.current.setMarkdown(value||'',false)},[value]);
  return <div ref={host}/>;
}

function DayOneGuide() {
  const [step, setStep] = useState(0);
  const steps = [
    { title: '确认练习接口', body: <><Paragraph>Restful Booker 是专门练习接口测试的公开服务，不需要注册。</Paragraph><a href="https://restful-booker.herokuapp.com/apidoc/index.html" target="_blank" rel="noreferrer">打开 API 文档 ↗</a><div className="endpoint-box"><code>GET https://restful-booker.herokuapp.com/booking</code></div><Paragraph type="secondary">先访问这个地址；看到 bookingid 列表就说明接口可用。</Paragraph></> },
    { title: '配置 Python', body: <><Paragraph>安装 Python 3.11 或 3.12，并勾选 Add Python to PATH。打开 PowerShell 执行：</Paragraph><pre className="guide-code"><code>{`python --version\nmkdir restful-booker-tests\ncd restful-booker-tests\npython -m venv .venv\n.\\.venv\\Scripts\\Activate.ps1\npython -m pip install pytest requests`}</code></pre><Paragraph type="secondary">若 PowerShell 阻止激活，先执行：<code>Set-ExecutionPolicy -Scope CurrentUser RemoteSigned</code></Paragraph></> },
    { title: '配置 Postman', body: <><Paragraph>Postman → New → HTTP Request，选择 GET，输入地址并点击 Send：</Paragraph><div className="endpoint-box"><code>https://restful-booker.herokuapp.com/booking/1</code></div><Paragraph>验收：状态码 200，响应包含 firstname、lastname 和 bookingdates。若 ID 1 不存在，先请求 booking 列表并换一个 ID。</Paragraph></> },
    { title: '首个 pytest 用例', body: <><Paragraph>在项目目录创建 <code>test_booking.py</code>：</Paragraph><pre className="guide-code"><code>{`import requests\n\nBASE_URL = "https://restful-booker.herokuapp.com"\n\ndef test_get_booking_list():\n    response = requests.get(f"{BASE_URL}/booking", timeout=10)\n    assert response.status_code == 200\n    bookings = response.json()\n    assert isinstance(bookings, list)\n    assert len(bookings) > 0\n    assert "bookingid" in bookings[0]`}</code></pre><Paragraph>执行 <code>pytest -v</code>。看到 <Tag color="green">1 passed</Tag> 即完成，并把结果与三个断言的含义写进学习笔记。</Paragraph></> },
  ];
  const item = steps[step];
  return <Card className="guide-card" title="🧭 第 1 天执行引导" extra={<Text type="secondary">60–90 分钟</Text>}><div className="guide-steps">{steps.map((x,i)=><button key={x.title} className={i===step?'active':''} onClick={()=>setStep(i)}><span>{i+1}</span>{x.title}</button>)}</div><div className="guide-content"><Title level={4}>{step+1}. {item.title}</Title>{item.body}<Space><Button disabled={!step} onClick={()=>setStep(step-1)}>上一步</Button><Button type="primary" disabled={step===steps.length-1} onClick={()=>setStep(step+1)}>下一步</Button></Space></div></Card>;
}

export function LearningPanel({client}) {
  const [overview,setOverview]=useState(null),[tasks,setTasks]=useState([]),[stats,setStats]=useState(null);
  const [month,setMonth]=useState(dayjs()),[checkin,setCheckin]=useState({actual_minutes:0,gains:'',blockers:'',tomorrow_focus:''});
  const [folders,setFolders]=useState([]),[notes,setNotes]=useState([]),[note,setNote]=useState(null),[query,setQuery]=useState(''),[trash,setTrash]=useState(false);
  const [saveState,setSaveState]=useState('已保存'), timer=useRef(), currentNote=useRef(null);
  const [taskModal,setTaskModal]=useState(null),[form]=Form.useForm();
  async function load(){await client.post(`${API}/schedule/reconcile`,{}); const [o,t,f]=await Promise.all([client.get(`${API}/overview`),client.get(`${API}/tasks`),client.get(`${API}/note-folders`)]); setOverview(o);setTasks(t);setFolders(f); if(o.latest_checkin?.checkin_date===String(o.today)) setCheckin(o.latest_checkin);}
  async function loadStats(value=month){setStats(await client.get(`${API}/stats?month=${value.format('YYYY-MM')}`))}
  async function loadNotes(){setNotes(await client.get(`${API}/notes?q=${encodeURIComponent(query)}&trash=${trash}`))}
  useEffect(()=>{load().catch(e=>message.error(e.message))},[]); useEffect(()=>{loadStats().catch(()=>{})},[month]); useEffect(()=>{loadNotes().catch(()=>{})},[query,trash]);
  useEffect(()=>{currentNote.current=note},[note]);
  async function toggle(task,checked){await client.put(`${API}/tasks/${task.id}`,{...task,status:checked?'completed':'pending'}); await load()}
  async function saveCheckin(){await client.put(`${API}/checkins/${overview.today}`,checkin);message.success('今日打卡已保存');await load()}
  function updateNote(patch){const next={...currentNote.current,...patch};setNote(next);setSaveState('保存中…');clearTimeout(timer.current);timer.current=setTimeout(()=>saveNote(next),1000)}
  async function saveNote(value=currentNote.current){if(!value)return;try{const saved=await client.put(`${API}/notes/${value.id}`,value);setNote(saved);setSaveState('已保存')}catch(e){setSaveState('保存失败');message.error(e.message)}}
  async function newNote(){const created=await client.post(`${API}/notes`,{title:'未命名笔记',content_markdown:'',tags:[],is_pinned:false});setNotes([created,...notes]);setNote(created)}
  async function uploadImage(blob){const fd=new FormData();fd.append('file',blob);const result=await client.post(`${API}/notes/${note.id}/attachments`,fd);return result.url}
  async function submitTask(){const values=await form.validateFields(); const body={...values,planned_date:values.planned_date.format('YYYY-MM-DD'),original_planned_date:taskModal?.original_planned_date||values.planned_date.format('YYYY-MM-DD')}; taskModal?.id?await client.put(`${API}/tasks/${taskModal.id}`,body):await client.post(`${API}/tasks`,body);setTaskModal(null);await load()}
  const phases=useMemo(()=>Object.entries(tasks.reduce((a,t)=>{(a[`${t.planned_date} · 第 ${t.day_number} 天 · ${t.phase}`]??=[]).push(t);return a},{})),[tasks]);
  if(!overview)return <Card loading/>;
  const tabs=[
    {key:'today',label:'🌱 今日学习',children:<div className="learning-today"><Row gutter={[16,16]}><Col xs={24} lg={16}><Card className="hero-card"><Text>现在最重要的一步</Text><Title level={2}>{overview.next_task?.title||'40 天计划已完成 🎉'}</Title><Paragraph>{overview.next_task?.details}</Paragraph><Progress percent={overview.progress}/></Card>{overview.next_task?.day_number===1&&<DayOneGuide/>}<Card title={`今日任务 · ${overview.today}`} className="section-card"><List dataSource={overview.today_tasks} locale={{emptyText:'今天没有任务'}} renderItem={t=><List.Item><Checkbox checked={t.status==='completed'} onChange={e=>toggle(t,e.target.checked)}><b>{t.title}</b><div><Text type="secondary">{t.details} · {t.expected_minutes} 分钟</Text></div><div><Tag>{t.category}</Tag>验收：{t.acceptance_criteria}</div></Checkbox></List.Item>}/></Card></Col><Col xs={24} lg={8}><Card title="📝 每日复盘"><Form layout="vertical"><Form.Item label="实际学习分钟"><InputNumber min={0} max={1440} value={checkin.actual_minutes} onChange={v=>setCheckin({...checkin,actual_minutes:v||0})}/></Form.Item>{[['gains','今日收获'],['blockers','遇到的问题'],['tomorrow_focus','明日重点']].map(([k,l])=><Form.Item label={l} key={k}><Input.TextArea rows={3} value={checkin[k]} onChange={e=>setCheckin({...checkin,[k]:e.target.value})}/></Form.Item>)}<Button type="primary" block onClick={saveCheckin}>完成今日打卡</Button></Form></Card></Col></Row></div>},
    {key:'plan',label:'🗺️ 学习计划',children:<><Space className="plan-toolbar"><Tag color="blue">原计划 {overview.plan.original_start_date} — {overview.plan.original_end_date}</Tag><Tag color={overview.deadline_risk?'red':'green'}>预计结束 {overview.plan.projected_end_date}</Tag><Button icon={<PlusOutlined/>} onClick={()=>{setTaskModal({});form.resetFields()}}>新增任务</Button></Space><div className="plan-list">{phases.map(([label,rows])=><Card size="small" title={label} key={label}>{rows.map(t=><div className="plan-task" key={t.id} onClick={()=>{setTaskModal(t);form.setFieldsValue({...t,planned_date:dayjs(t.planned_date)})}}><Checkbox checked={t.status==='completed'} onClick={e=>e.stopPropagation()} onChange={e=>toggle(t,e.target.checked)}/><span>{t.category==='复盘'?'✍️':'🧪'} {t.title}</span><Text type="secondary">{t.expected_minutes}m</Text></div>)}</Card>)}</div></>},
    {key:'calendar',label:'📅 打卡日历',children:<><Space className="stats-row"><DatePicker picker="month" value={month} onChange={setMonth}/><Statistic title="打卡天数" value={stats?.checkin_days||0} suffix="天"/><Statistic title="连续打卡" value={stats?.current_streak||0} suffix="天"/><Statistic title="总时长" value={Math.round((stats?.total_minutes||0)/60*10)/10} suffix="小时"/><Statistic title="任务完成率" value={stats?.task_completion_rate||0} suffix="%"/></Space><CalendarGrid month={month} stats={stats}/></>},
    {key:'notes',label:'📒 学习笔记',children:<div className="notes-layout"><aside><Space><Button icon={<FolderAddOutlined/>} onClick={async()=>{const name=prompt('文件夹名称');if(name){await client.post(`${API}/note-folders`,{name});setFolders(await client.get(`${API}/note-folders`))}}}>文件夹</Button><Button type="primary" icon={<PlusOutlined/>} onClick={newNote}>笔记</Button></Space><Input.Search placeholder="搜索标题和正文" allowClear onSearch={setQuery}/><Button type="text" onClick={()=>setTrash(!trash)}>{trash?'返回笔记':'🗑️ 回收站'}</Button>{folders.map(f=><div className="folder" key={f.id}>📁 {f.name}</div>)}</aside><section className="note-list"><List dataSource={notes} locale={{emptyText:<Empty description="还没有笔记"/>}} renderItem={n=><List.Item className={note?.id===n.id?'selected':''} onClick={()=>setNote(n)}><List.Item.Meta title={<>{n.is_pinned&&<PushpinFilled/>} {n.title}</>} description={(n.content_markdown||'空白笔记').slice(0,70)}/></List.Item>}/></section><main className="note-editor">{note?<><Space className="editor-head"><Input variant="borderless" value={note.title} onChange={e=>updateNote({title:e.target.value})}/><Text type={saveState==='保存失败'?'danger':'secondary'}>{saveState}</Text><Button icon={<SaveOutlined/>} onClick={()=>saveNote()}>保存</Button><Upload showUploadList={false} customRequest={async({file,onSuccess,onError})=>{try{await uploadImage(file);onSuccess()}catch(e){onError(e)}}}><Button icon={<UploadOutlined/>}>附件</Button></Upload><Button danger icon={<DeleteOutlined/>} onClick={async()=>{await client.delete(`${API}/notes/${note.id}`);setNote(null);loadNotes()}}/></Space><MarkdownEditor value={note.content_markdown} onChange={v=>updateNote({content_markdown:v})} onImage={uploadImage}/></>:<Empty description="选择或新建一篇笔记"/>}</main><Upload accept=".zip" showUploadList={false} customRequest={async({file,onSuccess,onError})=>{const fd=new FormData();fd.append('file',file);try{const r=await client.post(`${API}/imports/youdao`,fd);message.success(`导入 ${r.success.length}，重复 ${r.duplicates.length}`);loadNotes();onSuccess()}catch(e){message.error(e.message);onError(e)}}}><Button className="import-btn">导入有道 ZIP</Button></Upload></div>}
  ];
  return <div className="learning-space"><div className="learning-heading"><div><Text>个人成长</Text><Title level={2}>📚 学习空间</Title></div><Tag color="purple">{overview.current_phase}</Tag></div><Tabs items={tabs}/><Modal open={!!taskModal} title={taskModal?.id?'编辑任务':'新增任务'} onCancel={()=>setTaskModal(null)} onOk={submitTask}><Form form={form} layout="vertical"><Form.Item name="title" label="任务名称" rules={[{required:true}]}><Input/></Form.Item><Row gutter={12}><Col span={12}><Form.Item name="phase" label="阶段" rules={[{required:true}]}><Input/></Form.Item></Col><Col span={12}><Form.Item name="category" label="分类" initialValue="实操"><Input/></Form.Item></Col></Row><Form.Item name="details" label="操作说明"><Input.TextArea/></Form.Item><Form.Item name="acceptance_criteria" label="验收标准"><Input.TextArea/></Form.Item><Row gutter={12}><Col span={8}><Form.Item name="day_number" label="第几天" rules={[{required:true}]}><InputNumber/></Form.Item></Col><Col span={8}><Form.Item name="expected_minutes" label="分钟" initialValue={60}><InputNumber/></Form.Item></Col><Col span={8}><Form.Item name="planned_date" label="日期" rules={[{required:true}]}><DatePicker/></Form.Item></Col></Row><Form.Item name="status" hidden initialValue="pending"><Input/></Form.Item></Form></Modal></div>;
}

function CalendarGrid({month,stats}){const start=month.startOf('month'),days=month.daysInMonth(),blanks=(start.day()+6)%7;return <div className="calendar"><div className="weekdays">{['一','二','三','四','五','六','日'].map(x=><b key={x}>{x}</b>)}</div><div className="calendar-grid">{Array(blanks).fill(0).map((_,i)=><i key={`b${i}`}/>)}{Array.from({length:days},(_,i)=>{const key=month.date(i+1).format('YYYY-MM-DD'),d=stats?.days?.[key];return <div key={key} className={d?.minutes?'checked':''}><b>{i+1}</b><span>{d?.minutes?`${d.minutes}m`:'—'}</span><small>{d?.total?`${d.completed}/${d.total}`:''}</small></div>})}</div></div>}
