import React, { useEffect, useState } from 'react';
import { Alert, Button, Card, Col, Form, Input, Popconfirm, Row, Select, Space, Switch, Table, Tag, Typography, message } from 'antd';
import { DeleteOutlined, EditOutlined, PlusOutlined, ReloadOutlined } from '@ant-design/icons';

export function OaManagementPanel({ client }) {
  const [form] = Form.useForm();
  const [accounts, setAccounts] = useState([]);
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [editing, setEditing] = useState(null);
  async function load() { setLoading(true); try { const data = await client.get('/oa/admin/accounts'); setAccounts(data.accounts || []); } catch (error) { message.error(error.message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  function resetForm() { setEditing(null); form.resetFields(); form.setFieldsValue({ family_role: '家庭成员', is_enabled: true, approver_account_ids: [] }); }
  function beginEdit(record) { setEditing(record); form.setFieldsValue({ username: record.username, display_name: record.name, family_role: record.family_role || '家庭成员', is_enabled: record.is_enabled, approver_account_ids: record.approver_account_ids || [], password: '' }); }
  function reviewerOptions(accountId) { return accounts.filter((item) => item.is_enabled && item.id !== accountId).map((item) => ({ value: item.id, label: `${item.name}（${item.family_role || '家庭成员'}）` })); }
  async function submit(values) { setSaving(true); try { if (editing) { await client.put(`/oa/admin/accounts/${editing.id}`, { ...values, password: values.password || undefined }); message.success('人员信息已更新'); } else { await client.post('/oa/admin/accounts', values); message.success('人员已新增'); } resetForm(); await load(); } catch (error) { message.error(error.message); } finally { setSaving(false); } }
  async function toggle(record, is_enabled) { try { await client.put(`/oa/admin/accounts/${record.id}`, { display_name: record.name, family_role: record.family_role || '家庭成员', is_enabled, approver_account_ids: record.approver_account_ids || [] }); message.success(is_enabled ? '已启用' : '已停用'); await load(); } catch (error) { message.error(error.message); } }
  async function remove(record) { try { await client.delete(`/oa/admin/accounts/${record.id}`); message.success('人员已删除'); if (editing?.id === record.id) resetForm(); await load(); } catch (error) { message.error(error.message); } }
  const selectedReviewerOptions = reviewerOptions(editing?.id);
  return <Row gutter={[16, 16]}>
    <Col xs={24} xl={9}><Card title={editing ? '编辑小程序人员' : '新增小程序人员'} extra={editing && <Button onClick={resetForm}>取消编辑</Button>}><Alert type="info" showIcon message="新增人员会创建“账号登录”账号；微信一键登录用户首次登录后会自动出现在右侧列表中。" style={{ marginBottom: 16 }} /><Form form={form} layout="vertical" initialValues={{ family_role: '家庭成员', is_enabled: true, approver_account_ids: [] }} onFinish={submit}><Form.Item label="登录账号" name="username" rules={[{ required: !editing, message: '请输入登录账号' }]}><Input disabled={Boolean(editing)} placeholder="例如：baby_a" /></Form.Item><Form.Item label="昵称" name="display_name" rules={[{ required: true, message: '请输入昵称' }]}><Input placeholder="例如：小美" /></Form.Item><Form.Item label="家庭角色" name="family_role" rules={[{ required: true, message: '请输入家庭角色' }]}><Input placeholder="例如：宝宝、男朋友、女朋友" /></Form.Item>{(!editing || editing.login_method === '账号登录') && <Form.Item label={editing ? '新密码' : '登录密码'} name="password" rules={[{ required: !editing, message: '请输入至少 6 位密码' }]}><Input.Password placeholder={editing ? '不修改请留空' : '至少 6 位'} /></Form.Item>}<Form.Item label="审核人" name="approver_account_ids"><Select mode="multiple" placeholder="可选择多个审核人" options={selectedReviewerOptions} /></Form.Item><Form.Item name="is_enabled" valuePropName="checked"><Switch checkedChildren="启用" unCheckedChildren="停用" /></Form.Item><Button type="primary" htmlType="submit" loading={saving} icon={<PlusOutlined />}>{editing ? '保存修改' : '新增人员'}</Button></Form></Card></Col>
    <Col xs={24} xl={15}><Card title="小程序人员列表" extra={<Button icon={<ReloadOutlined />} loading={loading} onClick={load}>刷新</Button>}><Table rowKey="id" loading={loading} dataSource={accounts} pagination={{ pageSize: 8 }} scroll={{ x: 980 }} columns={[{ title: '昵称', dataIndex: 'name', width: 120 }, { title: '登录账号', dataIndex: 'username', width: 130 }, { title: '登录方式', dataIndex: 'login_method', width: 120 }, { title: '家庭角色', dataIndex: 'family_role', width: 110 }, { title: '审核人', render: (_, record) => (record.approver_account_ids || []).length ? <Space size={4} wrap>{record.approver_account_ids.map((id) => <Tag key={id}>{accounts.find((item) => item.id === id)?.name || '已移除人员'}</Tag>)}</Space> : '-' }, { title: '状态', width: 100, render: (_, record) => <Switch checked={record.is_enabled} checkedChildren="启用" unCheckedChildren="停用" onChange={(value) => toggle(record, value)} /> }, { title: '操作', width: 150, fixed: 'right', render: (_, record) => <Space size={6}><Button icon={<EditOutlined />} onClick={() => beginEdit(record)}>编辑</Button><Popconfirm title={`删除人员「${record.name}」？`} description="删除后该人员无法再登录小程序。" okText="删除" cancelText="取消" okButtonProps={{ danger: true }} onConfirm={() => remove(record)}><Button danger icon={<DeleteOutlined />}>删除</Button></Popconfirm></Space> }]} /><Typography.Paragraph type="secondary" style={{ marginTop: 16 }}>审核人按人员独立配置：A 可以选择 B、C；B 也可以选择 A、C。</Typography.Paragraph></Card></Col>
  </Row>;
}
