"""Versioned, structured zero-basics curriculum for Python and API automation."""

SEED_VERSION = "python_http_mastery_v1"

STAGES = [
    ("environment", "🧰", "工具与运行环境", "能解释代码如何从 VS Code 进入 Python 解释器，并独立准备隔离环境。"),
    ("network", "🌐", "网络与 HTTP", "能追踪一次接口请求的完整旅程，并按层定位网络问题。"),
    ("python", "🐍", "Python 零基础", "能读写接口测试需要的数据、控制逻辑、函数、模块、类和异常处理。"),
    ("requests", "📨", "从手工请求到 Python", "能把 Network、Postman 和 cURL 请求准确改写为 requests。"),
    ("pytest", "🧪", "Pytest 与测试设计", "能把脚本变成可重复执行、可定位失败并自动清理数据的测试。"),
    ("framework", "🏗️", "框架搭建与改造", "能从空目录搭建分层接口框架，并解释每层存在的原因。"),
    ("hotel", "🏨", "酒店项目实战", "能完成酒店接口的查询、鉴权、增删改查和回归。"),
    ("emote", "🌱", "Emote 工作迁移", "能安全迁移框架并完成 Emote 只读接口回归和证据输出。"),
]


def lesson(stage, slug, title, outcome, why, model, code, actions, rewrite, exercise, question, options, answer, explanation):
    return {
        "stage": stage, "slug": slug, "title": title, "outcome": outcome,
        "content": {
            "why": why,
            "mental_model": model,
            "journey": ["页面操作", "前端代码", "DNS", "TCP", "TLS", "HTTP", "网关", "后端", "数据库", "响应与页面"],
            "annotated_code": code,
            "follow_steps": actions,
            "prediction": "运行前先写下你认为会出现的结果；运行后对比实际结果，不一致时记录原因。",
            "rewrite_task": rewrite,
            "exercise": {"prompt": exercise, "hint": "先找输入、处理和输出，再一次只修改一个位置。"},
            "quiz": [{"question": question, "options": options, "answer": answer, "explanation": explanation}],
        },
    }


LESSONS = [
    lesson("environment", "python-runtime", "代码为什么能运行", "能说清源代码、解释器和输出的关系。",
        "零基础最容易把 VS Code、Python 和终端混成一个东西。先分清它们，后面的报错才知道去哪一层找。",
        "VS Code 像写字桌，.py 文件像说明书，Python 解释器才是真正逐行执行说明书的工人。",
        '# print 是 Python 提供的输出函数，用来观察程序结果\nprint("你好，接口自动化")  # 字符串会显示在终端中',
        ["在 VS Code 新建 api_learning 文件夹", "新建 hello.py 并逐字输入示例", "在终端运行 python hello.py", "修改文字后再次运行并比较输出"],
        "把输出内容改成“我正在学习请求和响应”，解释为什么只改引号里的文字。",
        "新建 about_me.py，输出你的岗位和学习目标，并保存终端运行结果。",
        "真正执行 .py 文件的是谁？", ["VS Code", "Python 解释器", "浏览器", "文件夹"], 1,
        "VS Code 负责编辑，Python 解释器读取并执行代码。"),
    lesson("environment", "terminal-path", "终端、路径和报错位置", "能进入正确目录、运行文件并读懂第一行错误。",
        "大量“代码有问题”其实是终端不在正确目录，或文件名写错。路径是自动化项目的基本坐标。",
        "终端当前目录像你站的位置；相对路径从脚下开始找，绝对路径从磁盘根目录开始找。",
        '# 查看当前目录中的文件\ndir  # PowerShell 列出文件\n# 运行当前目录里的脚本\npython .\\hello.py  # . 表示当前目录',
        ["观察 VS Code 终端提示符中的当前路径", "运行 dir 找到 hello.py", "故意输入错误文件名并保留报错", "从报错中指出文件名和错误原因"],
        "把 hello.py 移入 scripts 文件夹，分别用 cd 和相对路径运行它。",
        "解释 python: can't open file 报错通常应该先检查哪两件事。",
        "相对路径中的 . 表示什么？", ["磁盘根目录", "当前目录", "上级目录", "Python 安装目录"], 1,
        ". 表示当前目录，.. 才表示上级目录。"),
    lesson("environment", "venv-pip", "虚拟环境、pip 与依赖", "能创建虚拟环境并解释为什么项目要隔离依赖。",
        "不同项目可能需要不同版本的 requests 或 pytest。虚拟环境让项目依赖互不污染。",
        "虚拟环境像每个项目自己的工具箱；pip 是往工具箱里放工具的人，requirements.txt 是工具清单。",
        '# 创建项目专属虚拟环境\npython -m venv .venv  # -m 表示运行 Python 自带模块\n# 激活 Windows PowerShell 环境\n.\\.venv\\Scripts\\Activate.ps1  # 提示符会出现 .venv\n# 安装接口测试依赖\npython -m pip install requests pytest  # 只装进当前环境',
        ["创建 .venv", "激活后确认提示符变化", "安装 requests 和 pytest", "用 python -m pip list 检查依赖"],
        "新建 requirements.txt，逐行写 requests 和 pytest，再解释它与虚拟环境的关系。",
        "关闭终端后重新打开，完成激活并运行 python -m pytest --version。",
        "requirements.txt 的主要作用是什么？", ["执行 Python", "记录项目依赖", "保存测试结果", "连接数据库"], 1,
        "它记录可重复安装的依赖，虚拟环境负责隔离这些依赖。"),

    lesson("network", "request-journey", "一次接口请求的完整旅行", "能按顺序讲出请求从页面到数据库再返回的过程。",
        "接口自动化不是只发送一个 URL。知道请求经过哪些层，才能判断超时和错误属于前端、网络、网关还是后端。",
        "请求像快递：域名是地址簿，TCP 是通路，TLS 是加密包装，HTTP 是运单，网关分拣，后端处理，数据库取货。",
        '# 浏览器中打开开发者工具 Network\n# 操作酒店页面后选择 booking 请求\n# 依次记录 URL、Method、Status、Request、Response\nGET /booker/booking HTTP/1.1  # 请求行说明方法和路径',
        ["打开酒店页面和 Network", "刷新并找到 booking 请求", "记录请求 URL、方法和状态码", "画出页面到数据库再返回的十个节点"],
        "把请求旅行图中的“后端”和“数据库”交换，解释为什么交换后逻辑不合理。",
        "选择一个真实请求，为十个节点各写一句“这一层做什么”。",
        "HTTP 500 最可能说明请求已经到达哪一侧？", ["仅停在浏览器", "后端服务侧", "DNS 之前", "本地文件夹"], 1,
        "500 是服务器错误，通常说明请求已到达服务器或其上游。"),
    lesson("network", "url-dns", "URL、域名与 DNS", "能拆解 URL，并解释域名如何找到服务器。",
        "路径、查询参数或环境域名写错，都会请求到错误资源。自动化框架的 base_url 就来自这里。",
        "URL 是完整地址；DNS 只把域名翻译为 IP，具体资源仍由端口、路径和查询参数决定。",
        '# 用变量保存一个完整 URL\nurl = "https://www.inxpiration.cn/emote-test/api/posts?page=1"  # 协议+域名+路径+查询\nprint(url)  # 先观察完整地址',
        ["标出 https 协议", "圈出域名 www.inxpiration.cn", "找出路径 /emote-test/api/posts", "找出查询参数 page=1"],
        "把 page=1 改为 page=2，说明域名、路径和查询参数各自是否变化。",
        "拆解酒店查询详情 URL，写出协议、主机、路径参数和可能的端口。",
        "DNS 主要把什么转换为什么？", ["JSON 转字典", "域名转 IP", "端口转路径", "Token 转 Cookie"], 1,
        "DNS 负责域名解析，资源路径由 HTTP 请求继续传递。"),
    lesson("network", "tcp-tls", "TCP、TLS 与 HTTPS", "能区分连接、加密和 HTTP 业务数据。",
        "连接超时、证书错误和接口 500 是不同层的问题。区分 TCP、TLS、HTTP 才能正确排查。",
        "TCP 先建立可靠通路；TLS 在通路上确认身份并协商加密；之后才传输 HTTP 请求。",
        '# PowerShell 检查 HTTPS 端口是否可连接\nTest-NetConnection www.inxpiration.cn -Port 443  # 443 是常见 HTTPS 端口\n# 成功只说明网络端口可达，不代表业务接口一定正确',
        ["观察 TcpTestSucceeded", "理解三次握手用于建立连接", "查看浏览器地址栏证书信息", "区分连接失败、证书失败和 HTTP 失败"],
        "假设端口连接成功但返回 401，解释为什么不能说是 TCP 故障。",
        "为 DNS 失败、TCP 超时、TLS 证书错误、HTTP 500 各写一个排查动作。",
        "HTTPS 中负责加密 HTTP 内容的是哪一层？", ["DNS", "TLS", "JSON", "pytest"], 1,
        "TLS 提供身份校验和加密，HTTP 定义业务请求与响应。"),
    lesson("network", "http-anatomy", "HTTP 请求与响应的组成", "能从 Network 中准确找到方法、头、体、状态和响应。",
        "自动化代码的每个参数都对应 HTTP 报文的一部分。不了解报文，就只能盲目复制代码。",
        "请求包含请求行、Headers 和可选 Body；响应包含状态码、Headers 和 Body。",
        '# requests 参数与 HTTP 报文一一对应\nresponse = requests.get(  # GET 是请求方法\n    url,  # URL 决定目标资源\n    params={"page": 1},  # params 生成查询参数\n    headers={"Accept": "application/json"},  # headers 生成请求头\n    timeout=10,  # 最多等待，避免无限卡住\n)\nprint(response.status_code)  # 响应状态码\nprint(response.json())  # JSON 响应体转为 Python 数据',
        ["在 Network 查看 Headers", "分别找到 Query String 和 Request Payload", "查看 Response Headers", "查看 Preview/Response 中的 JSON"],
        "增加一个 X-Student: cling 请求头，解释它为什么不应该写进 params。",
        "把一条 Network 请求整理为方法、URL、Headers、Body、Status、Response 六栏。",
        "查询参数在 requests 中通常使用哪个参数？", ["params", "json", "cookies", "verify"], 0,
        "params 会编码到 URL 的 ? 后面；json 用于 JSON 请求体。"),
    lesson("network", "methods-idempotency", "方法、CRUD 与幂等性", "能按业务意图选择 HTTP 方法并判断重复调用风险。",
        "随机重试 POST 可能创建重复数据；理解方法语义和幂等性是稳定自动化的前提。",
        "GET 查询、POST 创建、PUT 整体更新、PATCH 局部更新、DELETE 删除；幂等表示重复执行最终状态相同。",
        '# 同一个查询重复执行通常不会改变服务器数据\nGET /booking/1  # 查询资源\n# 创建请求重复执行可能生成两条数据\nPOST /booking  # 创建资源，通常不幂等',
        ["把酒店 CRUD 与五种方法对应", "区分 PUT 与 PATCH", "讨论 DELETE 重复执行的状态变化", "判断哪些请求可安全自动重试"],
        "将“修改预约人的姓氏”分别写成 PUT 和 PATCH 的业务描述。",
        "列出一个不能盲目重试的 Emote 操作，并解释重复执行风险。",
        "哪个方法通常用于局部更新？", ["GET", "POST", "PATCH", "OPTIONS"], 2,
        "PATCH 表达局部更新；PUT 通常表达完整替换或整体更新。"),
    lesson("network", "auth-content", "鉴权、Cookie、Token 与请求体", "能区分登录凭据、Token、Cookie 和常见 Content-Type。",
        "401、403 和 415 经常来自鉴权或请求体格式，而不是接口不存在。",
        "登录用账号换取身份凭证；后续请求通过 Cookie 或 Authorization Header 携带凭证。Content-Type 告诉服务器如何解析 Body。",
        '# Bearer Token 放在 Authorization 请求头\nheaders = {"Authorization": "Bearer <运行时Token>"}  # 不把真实 Token 写进代码仓库\n# JSON 数据使用 json 参数并自动设置 application/json\nresponse = requests.post(url, json={"name": "测试用户"}, headers=headers, timeout=10)',
        ["观察登录响应中的 Token 或 Set-Cookie", "观察后续请求如何携带身份", "比较 application/json 与 form-data", "区分 401 未认证和 403 无权限"],
        "移除 Authorization 后预测状态码，再恢复请求头验证结果。",
        "写出 JSON、普通表单和文件上传三种请求体的适用场景。",
        "Bearer Token 通常放在哪里？", ["URL 域名", "Authorization Header", "响应状态码", "文件名"], 1,
        "Bearer Token 属于鉴权请求头，不应放在日志或课程笔记中。"),
    lesson("network", "status-timeout-debug", "状态码、超时与分层排错", "能根据现象选择正确的第一步排查动作。",
        "“接口失败”不是一个可定位的结论。需要先确认失败发生在 DNS、连接、TLS、HTTP 还是业务断言。",
        "先证明请求发到哪里，再看服务器返回什么，最后判断业务结果是否正确。",
        '# 分开设置连接和读取超时\nresponse = requests.get(  # 发送查询请求\n    url,  # 目标接口地址\n    timeout=(3, 10),  # 3 秒连接超时，10 秒读取超时\n)\nresponse.raise_for_status()  # 4xx/5xx 转为明确异常',
        ["无响应时先看 Network Timing", "4xx 检查请求和权限", "5xx 保存 request-id 与响应", "用 Charles 对比前端成功请求与脚本请求"],
        "把 timeout=(3, 10) 改为 (1, 30)，说明两个数字分别影响什么。",
        "为 DNS、连接、TLS、401、404、500、读取超时写一张排查顺序表。",
        "连接已建立但服务器迟迟不返回数据属于什么超时？", ["DNS 超时", "连接超时", "读取超时", "pytest 收集超时"], 2,
        "读取超时发生在连接建立之后等待响应数据的阶段。"),

    lesson("python", "python-values", "变量、类型与接口数据", "能用变量保存 URL、状态码和布尔判断。",
        "接口自动化就是不断准备输入、保存结果并比较预期。变量和类型是这些动作的基础。",
        "变量是带名字的盒子；字符串保存文本，整数保存状态码，布尔值保存真假，None 表示暂无值。",
        'base_url = "http://111.229.178.141/booker"  # 字符串：接口根地址\nstatus_code = 200  # 整数：响应状态码\nis_success = status_code == 200  # 布尔值：比较结果\ntoken = None  # 当前还没有 Token\nprint(base_url, is_success, token)  # 查看四个值',
        ["逐行输入变量", "使用 type 查看类型", "修改状态码预测布尔结果", "解释 = 与 == 的区别"],
        "用自己的变量名保存接口路径、期望状态码和是否需要鉴权。",
        "写一个脚本：保存实际状态码 404，并输出它是否等于预期 200。",
        "Python 中 == 的作用是什么？", ["赋值", "比较是否相等", "导入模块", "定义函数"], 1,
        "= 把值交给变量；== 比较两个值并产生布尔结果。"),
    lesson("python", "collections-json", "列表、字典与 JSON", "能读取接口列表和对象中的关键字段。",
        "JSON 数组会变成 Python 列表，JSON 对象会变成字典；绝大多数接口断言都依赖它们。",
        "列表按顺序装多条数据，字典用键找到一个字段。",
        'bookings = [{"bookingid": 1}, {"bookingid": 2}]  # 列表中放两个字典\nfirst = bookings[0]  # 下标 0 取得第一项\nbooking_id = first["bookingid"]  # 用键取得字段值\nprint(booking_id)  # 应输出 1',
        ["画出外层列表和内层字典", "取得第二个 bookingid", "故意写错键并观察 KeyError", "使用 .get 比较差异"],
        "给每个字典增加 guest 字段，再输出第二位客人的名字。",
        "从给定预约 JSON 中取出 firstname，并判断类型是否为字符串。",
        "JSON 对象通常转换为哪种 Python 类型？", ["list", "dict", "bool", "function"], 1,
        "JSON 对象是键值结构，对应 Python 字典。"),
    lesson("python", "conditions-loops", "条件、循环与批量检查", "能遍历响应列表并根据条件输出异常。",
        "接口经常返回多条数据，需要逐条检查；条件决定某条数据是否符合预期。",
        "for 像逐个检查清单，if 像每次检查时使用的判断规则。",
        'status_codes = [200, 200, 500]  # 模拟三次请求结果\nfor code in status_codes:  # 每次取出一个状态码\n    if code != 200:  # 如果不是成功状态\n        print("发现异常:", code)  # 只输出异常值',
        ["手算循环执行次数", "预测输出内容", "增加一个 404", "把条件改成 code >= 400"],
        "统计列表中成功和失败的数量，并解释循环变量每次保存什么。",
        "遍历预约列表，只输出 bookingid 大于 10 的记录。",
        "if 代码块何时执行？", ["条件为 True", "每次都执行", "程序结束后", "导入模块时才执行"], 0,
        "if 后的条件为 True 时，缩进代码块才执行。"),
    lesson("python", "functions", "函数、参数与返回值", "能把重复请求准备动作提取为函数。",
        "复制粘贴相同代码会让修改分散。函数给一段动作命名，并通过参数接收变化部分。",
        "函数像可重复使用的机器：参数是输入，函数体是处理，return 是输出。",
        'def build_url(base_url, booking_id):  # 定义函数和两个输入\n    path = f"/booking/{booking_id}"  # 根据 ID 组成路径\n    return base_url + path  # 返回完整 URL\n\nurl = build_url("http://111.229.178.141/booker", 2)  # 调用函数\nprint(url)  # 查看返回值',
        ["圈出定义和调用", "改变 booking_id", "把返回值保存为变量", "解释没有 return 会得到什么"],
        "增加 timeout 参数，让函数返回 URL 和 timeout 两个值。",
        "编写 build_headers(token)；有 Token 时返回 Authorization Header。",
        "return 的作用是什么？", ["结束电脑", "把结果交回调用处", "安装依赖", "发起 HTTP 请求"], 1,
        "return 把函数处理结果交回调用它的位置。"),
    lesson("python", "modules-classes", "模块、类与客户端", "能解释 import、类、实例和 self。",
        "自动化框架需要跨文件复用代码；类可以把配置和相关接口方法放在一个客户端对象中。",
        "模块是一个 Python 文件；类是设计图；实例是按设计图创建的真实工具；self 指当前这个工具。",
        'class BookerClient:  # 定义客户端设计图\n    def __init__(self, base_url):  # 创建实例时执行\n        self.base_url = base_url  # 保存属于该实例的地址\n\n    def booking_url(self, booking_id):  # 定义实例方法\n        return f"{self.base_url}/booking/{booking_id}"  # 使用实例配置\n\nclient = BookerClient("http://111.229.178.141/booker")  # 创建实例\nprint(client.booking_url(2))  # 调用实例方法',
        ["把类放入 booker_client.py", "在另一个文件 import", "创建 client 实例", "解释两个实例为什么可用不同 base_url"],
        "增加 timeout 实例属性，并在创建对象时传入。",
        "为客户端增加 headers 方法，返回 Accept: application/json。",
        "self.base_url 属于谁？", ["所有电脑", "当前客户端实例", "pytest 插件", "数据库表"], 1,
        "self 表示当前实例，因此不同客户端可以保存不同配置。"),
    lesson("python", "exceptions-logging", "异常、文件与日志", "能捕获网络异常并留下可排查信息。",
        "失败不可怕，丢失失败上下文才可怕。异常处理负责说明失败，日志负责留下时间和位置。",
        "try 尝试风险操作，except 处理已知失败，finally 做必须执行的收尾。",
        'import logging  # 导入日志模块\nimport requests  # 导入 HTTP 客户端\nlogging.basicConfig(level=logging.INFO)  # 设置日志级别\ntry:  # 开始可能失败的请求\n    response = requests.get("http://127.0.0.1:1", timeout=1)  # 故意访问无服务端口\nexcept requests.RequestException as error:  # 捕获 requests 网络异常\n    logging.error("请求失败: %s", error)  # 记录完整原因',
        ["运行并观察异常文本", "指出异常类型", "增加请求 URL 到日志", "确认日志中不记录密码和 Token"],
        "将错误同时写入 error.log，并说明为什么不能只写“请求失败”。",
        "捕获 Timeout 和 ConnectionError，分别输出中文排查提示。",
        "finally 最适合处理什么？", ["必须执行的清理", "定义变量类型", "DNS 解析", "安装 pytest"], 0,
        "finally 无论成功失败都会执行，适合关闭资源和清理数据。"),

    lesson("requests", "network-to-curl", "从 Network 到 cURL", "能逐项读懂浏览器复制的 cURL。",
        "cURL 是前端成功请求的可复制证据，也是手工请求迁移到 Python 的桥梁。",
        "-X 对应方法，URL 对应目标，-H 对应 Header，--data 对应 Body。",
        'curl -X GET "http://111.229.178.141/booker/booking" `  # 方法和 URL\n  -H "Accept: application/json"  # 请求头，希望收到 JSON',
        ["在 Network 复制 cURL", "删除 Cookie 等无关浏览器头", "在 PowerShell 运行", "比较浏览器与 cURL 响应"],
        "把查询列表 cURL 改为查询一个 bookingid，并说明只改了哪一部分。",
        "将一条 Emote 只读请求整理为最小可复现 cURL，不包含真实 Token。",
        "cURL 中 -H 表示什么？", ["请求头", "状态码", "文件夹", "测试函数"], 0,
        "-H 添加请求头；多个请求头可重复使用 -H。"),
    lesson("requests", "requests-get", "第一个 requests 查询", "能发送 GET 并检查状态码与 JSON。",
        "把手工请求写成 Python 后，才能重复执行、批量断言并进入自动化框架。",
        "requests.get 负责发送；Response 保存服务器返回的状态、头、正文和耗时。",
        'import requests  # 导入第三方 HTTP 库\nurl = "http://111.229.178.141/booker/booking"  # 保存查询地址\nresponse = requests.get(url, timeout=10)  # 发送 GET 并限制等待时间\nprint(response.status_code)  # 查看 HTTP 状态码\nprint(response.json())  # 把 JSON 响应转换为 Python 数据',
        ["安装 requests", "输入并运行脚本", "用 type 查看 response.json()", "故意写错路径观察状态码"],
        "增加 assert response.status_code == 200，并解释断言失败告诉了你什么。",
        "查询一个存在的 bookingid，断言响应是字典且包含 firstname。",
        "response.json() 的作用是什么？", ["发送请求", "解析 JSON 响应", "创建虚拟环境", "获取 DNS"], 1,
        "它把 JSON 文本解析为 Python 列表、字典等数据。"),
    lesson("requests", "requests-auth-body", "请求头、JSON 与鉴权", "能发送创建或鉴权请求，并保护敏感数据。",
        "POST 请求的 Body 和鉴权 Header 写错会导致 400、401、403 或 415。需要明确每个数据放在哪里。",
        "URL 定位资源，Header 描述格式和身份，JSON Body 携带业务数据。",
        'import requests  # 导入请求库\npayload = {"username": "admin", "password": "password123"}  # 仅酒店练习账号\nresponse = requests.post(  # 发送认证请求\n    "http://111.229.178.141/booker/auth",  # 认证地址\n    json=payload,  # 自动序列化 JSON 并设置 Content-Type\n    timeout=10,  # 避免无限等待\n)\ntoken = response.json()["token"]  # 从 JSON 中取出 Token\nprint("已获得 Token，长度:", len(token))  # 不打印 Token 本身',
        ["在 Postman 先验证认证", "运行 Python 请求", "观察 Request Headers", "确认日志不包含敏感值"],
        "把 payload 改为错误密码并预测状态码或响应内容，再恢复正确数据。",
        "写出携带 Cookie: token=... 的删除请求，但只使用运行时变量。",
        "requests 的 json 参数会自动做什么？", ["设置 JSON 请求体和 Content-Type", "保存数据库", "建立 pytest fixture", "解析 DNS"], 0,
        "json 参数序列化数据，并使用 application/json。"),

    lesson("pytest", "first-pytest", "从脚本到第一条 pytest", "能解释测试函数、执行、断言和报告。",
        "普通脚本只能告诉你输出；测试用例用断言自动判断结果，并能批量运行和报告失败。",
        "Arrange 准备、Act 执行、Assert 判断，是最基本的用例结构。",
        'import requests  # Arrange 前导入依赖\n\ndef test_booking_list_returns_200():  # test_ 开头才能被 pytest 收集\n    url = "http://111.229.178.141/booker/booking"  # Arrange：准备地址\n    response = requests.get(url, timeout=10)  # Act：发送请求\n    assert response.status_code == 200  # Assert：自动判断结果',
        ["保存为 test_booking.py", "运行 pytest -v", "故意把 200 改成 201", "读懂 expected 和 actual"],
        "增加断言：response.json() 必须是列表。",
        "编写查询不存在 ID 的用例，并根据真实接口约定断言。",
        "pytest 为什么能找到这个函数？", ["函数名以 test_ 开头", "调用了 print", "使用了 URL", "安装了 requests"], 0,
        "pytest 按测试发现规则收集 test_ 文件和 test_ 函数。"),
    lesson("pytest", "scenario-parametrize", "场景设计与参数化", "能把正常、边界和异常输入组织成独立报告。",
        "接口自动化的价值不是请求成功一次，而是稳定覆盖有意义的输入与预期。",
        "参数化把测试逻辑和测试数据分开，每组数据仍生成独立用例结果。",
        'import pytest  # 导入参数化能力\n\n@pytest.mark.parametrize("booking_id, expected", [  # 定义多组输入和预期\n    (1, 200),  # 正常或已有数据需要按环境调整\n    (999999999, 404),  # 不存在 ID\n    ("abc", 404),  # 非法格式\n])\ndef test_get_booking(client, booking_id, expected):  # 每组数据调用一次\n    response = client.get(f"/booking/{booking_id}")  # 执行请求\n    assert response.status_code == expected  # 对比该组预期',
        ["列出正常、边界、异常和权限场景", "只保留共同测试逻辑", "运行并观察三个测试 ID", "检查环境动态数据风险"],
        "增加空字符串和负数场景，并写出你依据的接口约定。",
        "为分页接口设计 page、size 的正常、边界和异常参数表。",
        "参数化最主要解决什么问题？", ["重复测试逻辑", "DNS 解析", "安装 Python", "生成 Token"], 0,
        "它让同一测试逻辑覆盖多组输入，减少复制代码。"),
    lesson("pytest", "fixture-cleanup", "Fixture、前置与清理", "能复用客户端并保证失败后也清理测试数据。",
        "用例重复创建客户端、登录和清理会变得难维护；清理遗漏还会污染测试环境。",
        "Fixture 在测试前准备资源，yield 把资源交给用例，yield 后负责清理。",
        'import pytest  # 导入 fixture\nfrom api.booker_client import BookerClient  # 导入业务客户端\n\n@pytest.fixture  # 声明可复用前置\ndef booker_client():  # fixture 名就是用例参数名\n    client = BookerClient()  # 测试前创建客户端\n    yield client  # 把客户端交给用例\n    client.close()  # 测试后无论成功失败都关闭连接',
        ["将 fixture 放入 conftest.py", "在用例参数中使用", "故意让断言失败", "确认 yield 后清理仍执行"],
        "增加 created_booking fixture：创建后 yield bookingid，最后删除。",
        "让测试中途失败并证明清理请求仍然发生。",
        "yield 后面的代码何时执行？", ["测试前", "测试结束后", "安装时", "永不执行"], 1,
        "fixture 的 yield 后代码用于测试结束后的清理。"),

    lesson("framework", "framework-layers", "从空目录理解框架分层", "能解释 api、config、data、tests、utils 各自职责。",
        "框架不是文件夹越多越专业。分层的目的，是让变化只影响一个位置，让测试表达业务意图。",
        "config 管环境，api 管接口动作，data 管输入，tests 管场景与断言，utils 管真正通用的小工具。",
        '# 项目结构不是 Python 代码，但每层都必须有明确责任\napi-test-project/  # 项目根目录\n├─ api/  # 请求层和业务客户端\n├─ config/  # 环境地址与非敏感配置\n├─ data/  # 测试输入\n├─ tests/  # 用例和断言\n├─ utils/  # 日志等通用能力\n└─ conftest.py  # pytest 公共 Fixture',
        ["在 VS Code 创建空目录", "为每层写一句职责", "把现有脚本按责任拆分", "检查是否出现只有一个文件却无必要的层"],
        "给三个示例判断归属：base_url、create_booking、异常请求数据。",
        "画出 test → BookerClient → HttpClient → server 的调用箭头。",
        "业务断言最应该放在哪一层？", ["tests", "config", "data", "DNS"], 0,
        "tests 负责场景与断言，客户端负责发送业务请求。"),
    lesson("framework", "http-client", "统一配置与请求层", "能封装 base_url、Session、timeout、headers 和错误证据。",
        "重复拼 URL、写 timeout 和公共 Header 会导致修改遗漏。统一请求入口让所有接口共享稳定行为。",
        "HttpClient 处理 HTTP 通用问题，不应该知道“预约”业务是什么意思。",
        'import requests  # 导入 HTTP 库\n\nclass HttpClient:  # 通用请求客户端\n    def __init__(self, base_url, timeout=10):  # 接收环境配置\n        self.base_url = base_url.rstrip("/")  # 防止双斜杠\n        self.timeout = timeout  # 保存默认超时\n        self.session = requests.Session()  # 复用连接和公共头\n\n    def request(self, method, path, **kwargs):  # 所有方法的统一入口\n        url = self.base_url + path  # 只在这里拼完整 URL\n        kwargs.setdefault("timeout", self.timeout)  # 调用方未指定时使用默认值\n        return self.session.request(method, url, **kwargs)  # 返回原始响应供断言',
        ["先找出现有重复代码", "创建 HttpClient", "封装 get/post/put/delete", "用日志输出方法、URL、状态码、耗时"],
        "增加 headers 合并：公共头保留，单次请求可以覆盖同名值。",
        "封装 patch 方法，并保证测试文件里不出现 requests.patch。",
        "为什么 request 应返回原始 Response？", ["让 tests 自己断言状态和业务数据", "为了保存密码", "为了绕过 HTTP", "为了创建 DNS"], 0,
        "请求层负责发送，具体预期属于测试场景。"),
    lesson("framework", "business-client-refactor", "业务客户端与重写用例", "能判断通用封装和业务封装的边界。",
        "测试中出现完整 URL 和重复 payload，会掩盖真正的测试意图。业务客户端用业务名称表达动作。",
        "HttpClient 说 get/post；BookerClient 说查询预约、创建预约、删除预约。",
        'class BookerClient:  # 酒店业务客户端\n    def __init__(self, http):  # 组合通用请求层\n        self.http = http  # 保存 HttpClient 实例\n\n    def get_booking(self, booking_id):  # 用业务名称描述动作\n        return self.http.get(f"/booking/{booking_id}")  # 具体路径集中在客户端\n\n# 用例只表达业务动作和预期\ndef test_booking_exists(booker_client):  # fixture 提供客户端\n    response = booker_client.get_booking(2)  # 查询预约\n    assert response.status_code == 200  # 验证业务预期',
        ["对比封装前后用例", "圈出测试意图", "将四个 CRUD 路径移入 BookerClient", "检查客户端中没有业务断言"],
        "把一个直接 requests.get 的旧用例改写为 booker_client 调用，并解释减少了什么重复。",
        "新增 list_bookings 和 partial_update_booking，保持命名表达业务。",
        "状态码断言为什么通常不放进 BookerClient？", ["不同测试场景可能期待不同状态码", "客户端不能返回数据", "Python 不支持 assert", "HTTP 没有状态码"], 0,
        "同一接口既要测成功也要测失败，预期应由用例决定。"),

    lesson("hotel", "hotel-observe", "从酒店页面追踪真实接口", "能把页面操作、Network、cURL 和业务结果对应起来。",
        "先理解真实业务动作产生什么请求，自动化用例才不是脱离业务的代码练习。",
        "页面是入口，Network 是事实，接口文档是约定，数据库结果是业务落点。",
        '# 酒店项目接口根地址\nBASE_URL = "http://111.229.178.141/booker"  # 统一部署地址\n# 查询预约列表\nresponse = requests.get(f"{BASE_URL}/booking", timeout=10)  # 对应前台/后台列表请求\nprint(response.status_code, response.json())  # 保存状态与响应证据',
        ["在酒店前台创建一次预约", "Network 找到创建请求", "在后台列表确认 ID", "复制 cURL 并用 Python 查询"],
        "改变入住日期，观察 Request Payload 哪个字段变化。",
        "整理预约流程的接口清单：页面动作、方法、路径、请求体、预期结果。",
        "接口自动化场景应优先来源于什么？", ["真实业务流程和接口约定", "随机方法", "文件夹数量", "代码行数"], 0,
        "测试围绕业务风险和约定设计，而不是为了写代码。"),
    lesson("hotel", "hotel-crud", "鉴权与完整 CRUD 链路", "能创建自己的数据并在失败时清理。",
        "完整链路能验证接口之间的数据传递，也能暴露鉴权和清理问题。",
        "先获取 Token，再创建并保存 ID，之后查询、修改、删除，最后确认资源不存在。",
        '# 伪代码展示数据如何在步骤间流动\ntoken = client.authenticate()  # 获取运行时鉴权\nbooking_id = client.create_booking(test_data)  # 创建并保存新 ID\nclient.get_booking(booking_id)  # 查询刚创建的数据\nclient.update_booking(booking_id, changed_data, token)  # 携带鉴权修改\nclient.delete_booking(booking_id, token)  # 清理自己创建的数据',
        ["准备唯一测试数据", "完成创建并保存 bookingid", "查询和修改同一 ID", "使用 finally 或 fixture 确保删除"],
        "故意让更新断言失败，验证清理仍能删除该 bookingid。",
        "完成一条全链路用例，并为每一步添加请求和响应证据。",
        "为什么不能固定删除 booking/2？", ["可能删除他人或公共数据", "数字不能用于 URL", "DELETE 不需要 ID", "pytest 不支持 DELETE"], 0,
        "自动化只能清理自己创建并记录的数据。"),
    lesson("hotel", "hotel-regression", "酒店接口回归与项目验收", "能独立运行项目并解释框架、场景和失败证据。",
        "稳定项目不仅要通过，还要让另一位测试工程师能安装、运行和定位失败。",
        "README 是入口，配置控制环境，测试报告说明结果，日志和 cURL 支持排错。",
        '# 在项目根目录安装和执行\npython -m pip install -r requirements.txt  # 按清单安装依赖\npython -m pytest -v --tb=short  # 运行并展示精简失败堆栈',
        ["从空终端按 README 安装", "运行全部正常与异常用例", "检查失败时有 URL、响应、cURL", "口述一次框架调用链"],
        "删除虚拟环境后按 README 重建，记录遗漏步骤并修正文档。",
        "向一个不懂项目的人讲清：为何分层、如何切环境、失败如何排查。",
        "可交付项目最重要的特征是什么？", ["别人可重复运行并定位失败", "文件夹最多", "代码不写注释", "只在作者电脑通过"], 0,
        "可重复、可理解、可排错比代码数量更重要。"),

    lesson("emote", "emote-readonly-map", "识别 Emote 只读接口", "能从真实页面筛选安全的 GET 查询并建立接口清单。",
        "工作项目首先要控制测试影响。只读迁移能练习真实鉴权和分页，同时避免制造业务脏数据。",
        "先用 Network 证明页面调用，再根据方法和业务含义判断是否只读。",
        '# Emote 测试环境由配置注入\nEMOTE_BASE_URL = "https://www.inxpiration.cn/emote-test/api"  # 测试环境 API 根地址\n# 示例只读查询路径，实际以 Network 为准\npath = "/posts?page=1&size=10"  # GET 查询参数不修改业务数据',
        ["登录在线预览", "在 Network 筛选 Fetch/XHR", "记录 GET 请求与页面功能", "排除 POST/PUT/PATCH/DELETE"],
        "给每个候选接口标注鉴权、分页、关键响应字段和是否安全。",
        "选出三个真实只读接口，并附上脱敏后的最小 cURL。",
        "第一阶段为什么只选择 GET 查询？", ["降低工作环境数据风险", "GET 一定没有响应", "Python 只支持 GET", "Token 只能用于 GET"], 0,
        "先在低风险范围验证框架，再扩大覆盖。"),
    lesson("emote", "emote-token-pagination", "Token、分页与环境配置", "能安全执行登录后的分页查询且不泄露凭据。",
        "真实项目通常需要 Bearer Token、环境切换和分页；这些是从练习项目迁移到工作的关键差异。",
        "账号换 Token，Token 只存在运行时；配置决定测试环境；参数决定分页数据。",
        'import os  # 读取运行环境变量\nimport requests  # 发送 HTTP 请求\nbase_url = os.getenv("EMOTE_API_BASE")  # 地址不硬编码在用例\ntoken = os.getenv("EMOTE_TOKEN")  # Token 不写入仓库\nheaders = {"Authorization": f"Bearer {token}"}  # 运行时组装鉴权头\nresponse = requests.get(  # 只读查询\n    f"{base_url}/posts",  # 业务路径\n    params={"page": 1, "size": 10},  # 分页参数\n    headers=headers,  # 携带身份\n    timeout=(3, 15),  # 连接和读取超时\n)',
        ["在终端临时设置环境变量", "运行查询不打印 Token", "断言分页结构和字段类型", "清理终端变量"],
        "把 page 改为 2，并断言返回页码或列表结构仍符合约定。",
        "为 page=0、size=0、超大 size 设计只读边界场景。",
        "敏感 Token 最适合保存在哪里？", ["Git 仓库", "运行时安全配置", "测试报告", "课程笔记"], 1,
        "凭据只在运行时提供，不进入代码、日志和笔记。"),
    lesson("emote", "emote-regression-evidence", "Emote 只读回归与工作证据", "能形成可重复执行、可复制排错的实际回归集合。",
        "工作价值来自快速确认风险和提供可定位证据，而不仅是显示 passed。",
        "每个失败应同时回答：请求了什么、服务器返回什么、耗时多久、前端成功请求与脚本有何差异。",
        '# 失败证据至少包含以下非敏感字段\nevidence = {  # 使用字典组织报告数据\n    "method": "GET",  # 请求方法\n    "url": response.request.url,  # 最终 URL 和查询参数\n    "status": response.status_code,  # HTTP 状态码\n    "elapsed_ms": round(response.elapsed.total_seconds() * 1000),  # 响应耗时\n    "response": response.text[:1000],  # 截断后的响应摘要\n}  # Authorization 必须从证据中排除',
        ["执行批准的只读接口集合", "保存分支与环境信息", "失败时生成脱敏 cURL", "与前端 Network 成功请求逐项对比"],
        "给证据增加 request-id 和 Content-Type，但明确排除 Authorization、Cookie、手机号和密码。",
        "完成至少一组 Emote 只读回归，并写出它节约了什么人工检查。",
        "好的自动化失败报告应该首先帮助什么？", ["快速复现和定位问题", "隐藏所有响应", "增加代码行数", "修改线上数据"], 0,
        "报告的核心是可复现、可定位，同时保护敏感信息。"),
]
